/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2016-12-23 13:31:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.postsCls;
import com.dao.adminCls;
import com.dao.categoryCls;
import com.Models.CategoryModel;
import com.Models.adminModel;
import com.Models.PostsModel;
import java.util.List;
import java.util.Arrays;
import java.util.ArrayList;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>Post | Edit</title>\r\n");
      out.write("<style>\r\n");
      out.write(".upDownButton {\r\n");
      out.write("            background: url(\"../imgFolder/up.png\") no-repeat scroll 0 0; bottom: 10px; right: 10px;\r\n");
      out.write("            position: fixed; width: 50px; height: 50px;\r\n");
      out.write("            cursor: pointer; display: none;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("     <!-- JQuery -->\r\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("     <script src=\"../js/formValidation.js\"></script> \r\n");
      out.write("    <script src=\"../js/myScript.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     <script src=\"../js/jquery.js\"></script>\r\n");
      out.write("     <script src=\"../js/jquery-ui.min.js\"></script> \r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/jquery-ui.min.css\">\r\n");
      out.write("     \r\n");
      out.write("          <!-- my Style -->\r\n");
      out.write("     <link href=\"../css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Start body Container -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row well\">\r\n");
      out.write("<div class=\"col-md-5\">\r\n");
      out.write("<h1>Current post:</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-5\">\r\n");
      out.write("<h4  style=\"color:red\">\r\n");

String msgError = (String) session.getAttribute("storeErrorMsg");

 if(!session.isNew() && msgError != null){
	 out.print(msgError);
     session.setAttribute("storeErrorMsg"," "); 
 }

	

      out.write("\r\n");
      out.write("</h4>\r\n");
      out.write("<h4  style=\"color:green\">\r\n");

String msgSeccess = (String) session.getAttribute("storeSuccessMsg");

 if(!session.isNew() && msgSeccess != null){
	 out.print(msgSeccess);
     session.setAttribute("storeSuccessMsg"," "); 
 }
	

      out.write("\r\n");
      out.write("</h4>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-2\">\r\n");
      out.write("<P><a class=\"btn btn-primary btn-lg\" href=\"dashboard.jsp\" role=\"button\">Back to Dashboard</a></P>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");

int postId = Integer.parseInt(request.getParameter("id"));
postsCls postClsObj = new postsCls();

List<PostsModel> dataforSingleShow = postClsObj.singleShow(postId);
  for(PostsModel editPost : dataforSingleShow){
	  

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row well\">  <!-- Start row -->\r\n");
      out.write(" <div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("  <div>\r\n");
      out.write("    <form action=\"../updatePost\" method=\"POST\" enctype=\"multipart/form-data\" id=\"postForms\">\r\n");
      out.write("    <div class=\"form-group\">  \r\n");
      out.write("     <label class=\"control-label\">Title:</label>\r\n");
      out.write("     <input type=\"text\" id=\"postTitles\" name=\"title\" class=\"form-control\" value=\"");
 out.print(editPost.getPostTitle()); 
      out.write("\">    \r\n");
      out.write("   <span class=\"msg\" id=\"postTitleMsg\"></span>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("     <div class=\"form-group\">  \r\n");
      out.write("     <label class=\"control-label\">Category:</label>\r\n");
      out.write(" ");

 String allCatagory = editPost.getCategory();
 String[] allCategoryArr = allCatagory.split(",");
 categoryCls categoryObj = new categoryCls();
 List<CategoryModel> categoryList = new ArrayList<CategoryModel>();
 
 categoryList = categoryObj.index();
 for(CategoryModel singleCategory : categoryList){
 
      out.write("\r\n");
      out.write("     <input type=\"checkbox\" class=\"form-control\" name=\"category\" value=\"");
 out.print(singleCategory.getId()); 
      out.write('"');
      out.write(' ');
      out.print( Arrays.asList(allCategoryArr).contains(singleCategory.getId())? "checked='checked'" : "" );
      out.write(">\r\n");
      out.write("     ");
 out.print(singleCategory.getCategory_title()); 
      out.write('\r');
      out.write('\n');
 
 }

      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     <div class=\"form-group\">  \r\n");
      out.write("     <label class=\"control-label\">Body:</label>\r\n");
      out.write("     <textarea id=\"postbody\" name=\"body\"  rows=\"10\" class=\"form-control\">");
out.print(editPost.getPostBody()); 
      out.write("</textarea> \r\n");
      out.write("    <span class=\"msg\" id=\"postBodyMsg\"></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("   <div class=\"form-group\">  \r\n");
      out.write("   <label class=\"control-label\">Current Image:</label>\r\n");
      out.write("   <div>\r\n");
      out.write("     ");

  String img = editPost.getPostImage().toString();
  
 if(img.equals("null")){ 
      out.write("\r\n");
      out.write("\tNo Image\r\n");
}else{
      out.write("\r\n");
      out.write("    <img src=\"../imgFolder/");
 out.print(editPost.getPostImage()); 
      out.write("\"  width=\"100px\" height=\"100px\"/> \t\r\n");
}
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write(" \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"form-group\">  \r\n");
      out.write("    <label class=\"control-label\">New Image:</label>\r\n");
      out.write("     <input type=\"file\" id=\"image\" name=\"image\" class=\" \">    \r\n");
      out.write("    </div>\r\n");
      out.write("    <input type=\"hidden\" name=\"currentPostId\" value=\"");
 out.print(editPost.getId()); 
      out.write("\"></input>\r\n");
      out.write("    <input type=\"hidden\" name=\"currentImgName\" value=\"");
 out.print(editPost.getPostImage()); 
      out.write("\"></input>\r\n");
      out.write("    \r\n");
      out.write("    <input type=\"submit\" value=\"Update now\" class=\"btn btn-success btn-lg btn-block\">\r\n");
      out.write("    \r\n");
      out.write("   </form>\r\n");
      out.write(" ");
} 
      out.write("\r\n");
      out.write(" </div> \r\n");
      out.write(" </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</div> <!-- End Blog body row -->\r\n");
      out.write(" <div class=\"upDownButton\"></div> \r\n");
      out.write("</div> <!-- End Container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write(" <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
