/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2016-12-23 13:33:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.postsCls;
import com.dao.adminCls;
import com.Models.adminModel;
import com.Models.PostsModel;
import java.util.List;
import java.util.ArrayList;
import com.dao.categoryCls;
import com.Models.CategoryModel;

public final class singleShow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>Admin | Create </title>\r\n");
      out.write("<style>\r\n");
      out.write(".upDownButton {\r\n");
      out.write("            background: url(\"../imgFolder/up.png\") no-repeat scroll 0 0; bottom: 10px; right: 10px;\r\n");
      out.write("            position: fixed; width: 50px; height: 50px;\r\n");
      out.write("            cursor: pointer; display: none;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"../css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("     <!-- JQuery -->\r\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"../js/myScript.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     <script src=\"../js/jquery.js\"></script>\r\n");
      out.write("     <script src=\"../js/jquery-ui.min.js\"></script> \r\n");
      out.write("     <link rel=\"stylesheet\" href=\"../css/jquery-ui.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main_container\">\r\n");
      out.write("\r\n");

String loginId = (String) session.getAttribute("loginID");
if(!session.isNew() && session.getAttribute("loginID") != null){
	adminCls adminClsObj = new adminCls();
	List<adminModel> selectedAdmin = adminClsObj.getAdminInfo(loginId);
	for(adminModel userInfo : selectedAdmin ){

      out.write(" \r\n");
      out.write("<!-- Admin login Navbar -->\r\n");
      out.write("  \r\n");
      out.write("<!-- End Admin login Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-default navbar-fixed-top\">\r\n");
      out.write("  <div class=\"navbar-header\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"about.jsp\">Welcome : </a>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"contact.jsp\">");
 out.print(userInfo.getAdminName()); 
      out.write("</a>              \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li><a href=\"dashboard.jsp\">Dashboard</a></li>      \r\n");
      out.write("      </ul>\r\n");
      out.write("      \r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"../adminLogout?action=logout\">LOGOUT</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"adminNav\"></nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
	
// session.setAttribute("loginID", null);
	}
}

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <!-- body contain section -->\r\n");
      out.write("  <section class=\"content_area\">\r\n");
      out.write("  \r\n");
      out.write("  ");

int postId = Integer.parseInt(request.getParameter("id"));
postsCls postClsObj = new postsCls();

List<PostsModel> dataforSingleShow = postClsObj.singleShow(postId);

 for(PostsModel singlePost  : dataforSingleShow){	

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-12\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">  <!-- Start row -->\r\n");
      out.write(" <div class=\"col-md-8\">\r\n");
      out.write(" <div class=\"col-md-12\"><h2>Post view: </h2></div>\r\n");
      out.write("  <div class=\"col-md-12\"><hr></div>\r\n");
      out.write(" <div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("\r\n");
      out.write("  ");

  String img = singlePost.getPostImage().toString();
  
 if(img.equals("null")){ 
      out.write("\r\n");
      out.write("\tNo Image\r\n");
}else{
      out.write("\r\n");
      out.write("    <img src=\"../imgFolder/");
 out.print(singlePost.getPostImage()); 
      out.write("\"  width=\"500px\" height=\"400px\"/> \t\r\n");
}
      out.write("\r\n");
      out.write("  </div>  \r\n");
      out.write("\r\n");
      out.write(" <div class=\"post col-md-12\">\r\n");
      out.write("   <h4>");
 out.print(singlePost.getPostTitle()); 
      out.write("</h4>\r\n");
      out.write("   <p>");
out.print(singlePost.getPostBody()); 
      out.write("</p> \r\n");
      out.write("  </div>\r\n");
      out.write("   \r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"col-md-4  well\">\r\n");
      out.write(" \r\n");
      out.write("  <dl class=\"dl-horizontal\">\r\n");
      out.write("  <dt>Category:</dt>\r\n");
      out.write("  <dd>\r\n");
      out.write("   ");

 String allCatagory = singlePost.getCategory();
 String[] allCategoryArr = allCatagory.split(",");
 
 for(int i=0; i<allCategoryArr.length; i++){
	 int CategoryId = Integer.parseInt(allCategoryArr[i]);
	 	 categoryCls categoryClsObj = new categoryCls();
	     List<CategoryModel> dataforShow = categoryClsObj.singleShow(CategoryId);
	     for(CategoryModel singleCategory : dataforShow){ 
      out.write("\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <p class=\"btn btn-default\">");
 out.print(singleCategory.getCategory_title()); 
      out.write("</p>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t     ");
 }
	
    }
 
      out.write("\r\n");
      out.write("  </dd>\r\n");
      out.write("  </dl> \r\n");
      out.write(" \r\n");
      out.write(" <dl class=\"dl-horizontal\">\r\n");
      out.write("  <dt>Create at :</dt>\r\n");
      out.write("  <dd>");
out.print(singlePost.getCreate_at()); 
      out.write("</dd>\r\n");
      out.write("</dl>\r\n");
      out.write("\r\n");
      out.write(" <dl class=\"dl-horizontal\">\r\n");
      out.write("  <dt>Last update :</dt>\r\n");
      out.write("  <dd>\r\n");
      out.write("  ");

  if(singlePost.getModify_at() == null){
	  out.print("Not yeat.");
  }else{
	  out.print(singlePost.getModify_at()); 
  }
   
      out.write("\r\n");
      out.write("  </dd>\r\n");
      out.write("</dl>\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write(" <div class=\"col-md-6\">\r\n");
      out.write("   <a href=\"../editPost?id=");
 out.print(singlePost.getId()); 
      out.write("\"\" class=\"btn btn-primary btn-block\">Edit</a>\r\n");
      out.write(" </div>\r\n");
      out.write("  <div class=\"col-md-6\">\r\n");
      out.write("   <a href=\"../deletePost?id=");
 out.print(singlePost.getId()); 
      out.write("\" class=\"btn btn-danger btn-block\">Delete</a>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write(" <div class=\"col-md-12\">\r\n");
      out.write("   <a href=\"dashboard.jsp\" class=\"btn btn-default btn-block\"> << Back</a>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("</div> <!-- End Blog body row -->\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"upDownButton\"></div> \r\n");
      out.write("   \r\n");
      out.write("  </section>\r\n");
      out.write(" <!-- End body contain section -->\r\n");
      out.write("  \r\n");
      out.write("  <footer class=\"footer_area\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xs-12\">\r\n");
      out.write("                    <div class=\"copyright\">\r\n");
      out.write("                        <p>&copy; Copyright Md Imran hossain.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer> \r\n");
      out.write("  </div>     <!-- End container -->\r\n");
      out.write("</div>\r\n");
      out.write(" <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
